---
abstract: 'Prefix comments in Test::More output'
author:
  - "['Peter Sergeant <pete@clueball.com>']"
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-More-Prefix
requires:
  IO::Scalar: 0
  Moose: 0
  Test::Builder: 0
  Test::More: 0
version: 0.003
